name: 游戏内报错反馈
description: 报告 Minecraft 运行时崩溃 | 
title: "[启动崩溃]: "
labels: ["Minecraft-Crash"]
body:
  - type: markdown
    attributes:
      value: |
        __！！！关于 PCL2 启动器而非 Minecraft 内的问题请移步 PCL2 问题反馈！！！__  
        [PCL2 问题反馈](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/issues/new?assignees=&labels=PCL-Problem&projects=&template=PCL-Problem.yml&title=%5BPCL+%E5%90%AF%E5%8A%A8%E5%99%A8%E9%97%AE%E9%A2%98%5D%3A+)
        
        __感谢对项目的支持与关注。在提出问题之前，请确保你已查看项目主页的文档__  
        [主页文档](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/blob/master/README.md)

        __！！！请仔细阅读每项的描述后提交，这样可以更快确定问题并提供解决方案！！！__

  - type: checkboxes
    attributes:
      label: "确定启动器为版本最新"
      description: |
        __PCL2 启动器（最新 V2.6.13）: 进入游戏后会直接提示更新，也可点击 ***设置-启动器-检查更新*** 即可手动检查启动器更新__  
        __HMCL 启动器（最新 V3.5.5）: 进入游戏后会直接提示更新__  
      options:
       - label: 我确保自己的启动器正处于最新版本
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minecraft 游戏报错输出
      description: |
        __PCL2 启动器如何输出报错__  
        在错误发生后会产生提示框报告发生的错误,  如果其提供了一些字段用于确定报错，请将截图与报错文件一并发送  
        如果显示没有确定报错原因, 点击 **导出错误报告** 后选择桌面位置保存, 保存后拖拽上传到该栏里即可发送  
    validations:
      required: true
