name: PCL2 启动器问题反馈
description: 报告 PCL2 启动器问题 | 
title: "[PCL 启动器问题]: "
labels: ["PCL-Problem"]
body:
  - type: markdown
    attributes:
      value: |
        __！！！关于 Minecraft 内问题而非 PCL 启动器的问题请移步 Minecraft 问题反馈！！！__  
        [Minecraft 问题反馈](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/issues/new?assignees=&labels=Minecraft-Crash&projects=&template=Minecraft-Crash.yml&title=%5B%E5%90%AF%E5%8A%A8%E5%B4%A9%E6%BA%83%5D%3A+)

        __感谢对项目的支持与关注。在提出问题之前，请确保你已查看文档__  
        [项目文档](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/blob/master/README.md)

        __！！！请仔细阅读每项的描述后提交，这样可以更快确定问题并提供解决方案！！！__

  - type: checkboxes
    attributes:
      label: "确定启动器为版本最新"
      description: |
        __PCL2 启动器（最新 V2.6.13）: 进入游戏后会直接提示更新，也可点击 ***设置-启动器-检查更新*** 即可手动检查启动器更新__  
      options:
       - label: 我确保自己的启动器正处于最新版本
         required: true

  - type: textarea
    attributes:
      label: PCL 问题详细
      description: |
        提交 PCL 问题详细或提交截图  
    validations:
      required: true
